# Generated by Django 6.0.1 on 2026-01-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCloseMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('HARD', 'Hard Close'), ('SOFT', 'Soft Close')], default='HARD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='close_mode', to='auctions.auction')),
            ],
        ),
    ]
