# Generated by Django 6.0.1 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_close', '0001_initial'),
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuctionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_anti_sniping_enabled', models.BooleanField(default=True)),
                ('default_threshold_minutes', models.PositiveIntegerField(default=5)),
                ('default_extension_minutes', models.PositiveIntegerField(default=5)),
                ('default_max_extensions', models.PositiveIntegerField(default=10)),
                ('default_close_mode', models.CharField(choices=[('HARD', 'Hard Close'), ('SOFT', 'Soft Close')], default='SOFT', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Global Auction Settings',
            },
        ),
        migrations.CreateModel(
            name='AntiSnipingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('threshold_minutes', models.PositiveIntegerField(default=5, help_text='If bid placed within this many minutes of end, trigger extension')),
                ('extension_minutes', models.PositiveIntegerField(default=5, help_text='Number of minutes to extend auction')),
                ('max_extensions', models.PositiveIntegerField(default=10, help_text='Maximum number of extensions allowed')),
                ('extensions_used', models.PositiveIntegerField(default=0)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anti_sniping', to='auctions.auction')),
            ],
            options={
                'verbose_name_plural': 'Anti-Sniping Settings',
            },
        ),
    ]
