# Generated by Django 6.0.1 on 2026-01-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('buyer_percent', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('transport_note', models.TextField(default='Transport charges are paid by Buyer directly to Seller')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
