# Generated by Django 5.2.4 on 2025-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincommission',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
