# Generated by Django 6.0.1 on 2026-01-14 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=10)),
                ('stars', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='escrow.escrow')),
            ],
        ),
    ]
