# Generated by Django 6.0.1 on 2026-01-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('LIVE', 'Live'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='auctions.auction')),
            ],
        ),
    ]
